spring:
  profiles:
    active: local

---
spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto : create-drop # update
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/testdb
    username: sa
    password:
    initialization-mode: always
  h2:
    console:
      enabled: true